### ISSUE TITLE
How about pg_contrib?

### ISSUE THREAD

**Issue by mhenrixon** [express42-cookbooks/postgresql_lwrp#17]
Love the work you've don here but I miss quite a few things from contrib. Any chance that would be looked at in the near future?

**Comment by sample** [comment]
Could you please explain what do you mean by pg_contrib? We're going to add lwrp for managing extensions, but no estimates now.

**Comment by mhenrixon** [comment]
Well that is sort of what I am asking for. Right now I keep running into stuff like 

> ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/hstore.control": No such file or directory

This is happening because `postgresql-9.4-contrib isn't installed. I can work around it for now but the lwrp should take peoples wish to have contrib installed into consideration when installing the rest of the packages.

**Comment by Artemmkin** [comment]
We added new resources that allow to install extensions from postgresql-contrib subpackage, which comes installed, as well as from http://pgxn.org
